### ISSUE TITLE
No tab selected by default which makes the button broken

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/log-detective-website#149]
![image](https://github.com/user-attachments/assets/d1814ece-57ee-4d7a-83a2-5d85637e6690)

This is how our site looks when it's first loaded. Sadly no tab is selected so hitting "Let's go" does nothing and throws an exception in the js console:
```
Error: No matching clause: 
    at Object.app$homepage_validation$validate [as validate] (homepage_validation.cljs:13:3)
    at app$homepage$on_submit (homepage.cljs:35:4)
    at Object.eval [as cljs$core$IFn$_invoke$arity$1] (core.cljs:1159:5)
    at Function.eval [as cljs$core$IFn$_invoke$arity$3] (core.cljs:3940:40)
    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (core.cljs:3936:7)
    at Function.eval [as cljs$core$IFn$_invoke$arity$2] (core.cljs:3971:7)
    at G__23396__delegate (template.cljs:73:21)
    at G__23396 (template.cljs:72:25)
    at HTMLUnknownElement.callCallback (react-dom.development.js:150:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:200:16)
app$homepage_validation$validate @ homepage_validation.cljs:13
app$homepage$on_submit @ homepage.cljs:35
eval @ core.cljs:1159
eval @ core.cljs:3940
eval @ core.cljs:3936
eval @ core.cljs:3971
G__23396__delegate @ template.cljs:73
G__23396 @ template.cljs:72
callCallback @ react-dom.development.js:150
invokeGuardedCallbackImpl @ react-dom.development.js:200
invokeGuardedCallback @ react-dom.development.js:257
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:271
executeDispatch @ react-dom.development.js:562
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:584
forEachAccumulated @ react-dom.development.js:663
runEventsInBatch @ react-dom.development.js:817
handleTopLevel @ react-dom.development.js:825
batchedUpdates$1 @ react-dom.development.js:20440
batchedUpdates @ react-dom.development.js:2152
dispatchEvent @ react-dom.development.js:4906
eval @ react-dom.development.js:20491
exports.unstable_runWithPriority @ scheduler.development.js:256
interactiveUpdates$1 @ react-dom.development.js:20490
dispatchInteractiveEvent @ react-dom.development.js:2171

react-dom.development.js:290 Uncaught Error: No matching clause: 
```

**Comment by TomasTomecek** [comment]
Fixed by https://github.com/fedora-copr/log-detective-website/pull/151
