### ISSUE TITLE
500 for a failed srpm build in copr

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-copr/log-detective-website#73]
```
Oops!
Server error: 500

expected str, bytes or os.PathLike object, not NoneType

```

input: 6885316
srpm-builds

from logs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/fastapi/routing.py", line 169, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/backend/api.py", line 128, in get_build_logs_with_chroot
    logs=provider.fetch_logs(),
         ^^^^^^^^^^^^^^^^^^^^^
  File "/src/backend/fetcher.py", line 28, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/src/backend/fetcher.py", line 113, in fetch_logs
    baseurl = os.path.dirname(build.source_package.get("url", ""))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I guess this is what happens:
```
In [3]: print({"url": None}.get("url", ""))
None
```

**Comment by TomasTomecek** [comment]
```
In [13]: build = c.build_proxy.get(6885316)

In [14]: print(build)
Munch({'chroots': ['fedora-rawhide-x86_64', 'fedora-rawhide-aarch64', 'fedora-rawhide-i386', 'fedora-rawhide-ppc64le', 'fedora-39-x86_64', 'fedora-38-x86_64', 'fedora-38-i386', 'fedora-39-i386', 'fedora-38-aarch64', 'fedora-38-ppc64le', 'fedora-39-aarch64', 'fedora-39-ppc64le'], 'ended_on': 1704977896, 'id': 6885316, 'is_background': False, 'ownername': '@meta', 'project_dirname': 'time', 'projectname': 'time', 'repo_url': '/api_3/build/6885316', 'source_package': {'name': None, 'url': None, 'version': None}, 'started_on': 1704977804, 'state': 'failed', 'submitted_on': 1704977794, 'submitter': 'packit', '__response__': <Response [200]>, '__proxy__': <copr.v3.proxies.build.BuildProxy object at 0x7fd8a74d5880>})

In [15]: print(build.chroots)
['fedora-rawhide-x86_64', 'fedora-rawhide-aarch64', 'fedora-rawhide-i386', 'fedora-rawhide-ppc64le', 'fedora-39-x86_64', 'fedora-38-x86_64', 'fedora-38-i386', 'fedora-39-i386', 'fedora-38-aarch64', 'fedora-38-ppc64le', 'fedora-39-aarch64', 'fedora-39-ppc64le']

In [16]: print(build.source_package)
{'name': None, 'url': None, 'version': None}
```

Can someone please explain this to me?

**Comment by FrostyX** [comment]
> In [16]: print(build.source_package)
> {'name': None, 'url': None, 'version': None}

The package failed during SRPM build phase, so any sources weren't imported to the Copr DistGit, and stored into the database. Even if you open the build https://copr.fedorainfracloud.org/coprs/g/meta/time/build/6885316/ the sources section is empty

![Screenshot_2024-01-11_15-19-19](https://github.com/fedora-copr/log-detective-website/assets/2151771/4a6b8a73-d061-438e-9a6f-aaeb34884663)

**Comment by nikromen** [comment]
any ideas how to retrieve base for log URL (https://download.copr.fedorainfracloud.org/results/@meta/time/srpm-builds/06885316/) from python-copr in this case then?

**Comment by FrostyX** [comment]
I wouldn't do anything complicated.

```python
from copr.v3 import Client
client = Client.create_from_config_file();
build = client.build_proxy.get(6885316)
print("https://download.copr.fedorainfracloud.org/results/{0}/{1}/srpm-builds/{2:08}"
      .format(build.ownername, build.project_dirname, build.id))
```

**Comment by kwk** [comment]
> I wouldn't do anything complicated.
> 
> ```python
> from copr.v3 import Client
> client = Client.create_from_config_file();
> build = client.build_proxy.get(6885316)
> print("https://download.copr.fedorainfracloud.org/results/{0}/{1}/srpm-builds/{2:08}"
>       .format(build.ownername, build.project_dirname, build.id))
> ```

Thank you @FrostyX we're essentially using that now [here](https://github.com/kwk/llvm-daily-fedora-rpms/blob/8aed01be309b3027a4678756348dec735fdc3aa1/github/functions.sh#L175-L183):

```bash
    # Treat errors with no build logs as unknown and tell user to visit the
    # build URL manually.
    if [ "$build_log_url" == "NOTFOUND" ]; then
      # See https://github.com/fedora-copr/log-detective-website/issues/73#issuecomment-1889042206
      source_build_log_url="https://download.copr.fedorainfracloud.org/results/$project/srpm-builds/$(printf "%08d" $build_id)/builder-live.log.gz"
      >&2 echo "No build log found. Falling back to scanning the SRPM build log: $source_build_log_url".

      source_build_log_file=$(mktemp)
      curl -sL $source_build_log_url | gunzip -c > $source_build_log_file
```
